;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        projectile-persp-switch-project
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        isearch-abort
        isearch-forward-regexp
        ))
